# Generated by Django 4.0.2 on 2022-02-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefile',
            name='my_resume',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
