# Generated by Django 4.0.2 on 2022-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_resumefile_my_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRemarkableWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/works')),
                ('works_links', models.URLField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ResumeFile',
        ),
    ]
